package com.chenwei666.netserial.navigation;

public enum FeatureId {
    USB_CONNECTIONS,
    REMOTE_CONNECTIONS,
    SESSION_WORKSPACE,
    TERMINAL_WORKSPACE,
    AI_COPILOT,
    COMMAND_LIBRARY,
    NETWORK_TOOLS,
    OPERATIONS_CENTER,
    ADVANCED_TOOLKIT,
    CHANGE_TASK,
    CONFIG_DIFF,
    CONFIG_SNAPSHOTS,
    DEVICE_MEMORY,
    APP_SETTINGS,
    AI_SETTINGS
}
